### ISSUE TITLE
fix: add poetry plugin to export in setup action

### ISSUE THREAD

**Issue by JaeAeich** [elixir-cloud-aai/cookiecutter-python#66]
In latest version of poetry, export plugin in not present, we have to manually add it.

Change `setup/action.yaml`:

```yaml
    - name: Add plugin to be able to export
      run: |
        poetry self add poetry-plugin-export
      shell: bash

```
